[project]
name = "clone-all-repo"
version = "0.1.0"
description = "Clone all git repos from repos.yaml"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "click>=8.1.8",
    "gitpython>=3.1.44",
    "loguru>=0.7.3",
    "pyyaml>=6.0.2",
    "tqdm>=4.67.1",
]

[project.scripts]
clone-all-repo = "car.cli:click_main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ['src/car']

[[tool.uv.index]]
name = "aliyun"
url = "https://mirrors.aliyun.com/pypi/simple/"
default = true

[tool.ruff.lint]
ignore = ["F821", "E501"]
select = [
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # isort
    "I",
]
